In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
print(a.shape)

(2, 7)


In [5]:
# Get the specific elements [r,c]

print(a[1,5])

13


In [6]:
# get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [7]:
# get a specific column
print(a[:,2])

[ 3 10]


In [8]:
# slicing
print(a[0,1:6:2])

[2 4 6]


3D array example:

In [9]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [10]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
print(b.shape)

(2, 2, 2)


In [12]:
# getting a specific number:(work outside in)
print(b[0,1,1])

4


In [13]:
print(b[:,1,:])

[[3 4]
 [7 8]]
