In [1]:
import numpy as np

In [2]:
#All zeros matriz
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
#all ones matrix:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [5]:
# any other number(full_like):
np.full_like(a,2)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [6]:
# random decimal numbers:
np.random.rand(3,3)


array([[0.20384265, 0.32604973, 0.84869635],
       [0.05196923, 0.93277991, 0.35979365],
       [0.52591756, 0.11805872, 0.98268443]])

In [7]:
np.random.randint(1,7,size=(3,3)) #(start,stop,size)

array([[5, 3, 6],
       [6, 1, 1],
       [5, 6, 6]])

In [8]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# repeat on array:
arr=np.array([[1,2,3]])
arr1=np.repeat(arr,3,axis=0) # bcz axis=0, it repeat for every row
print(arr1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
arr=np.array([[1,2,3]])
arr1=np.repeat(arr,3,axis=1) # bcz axis=1, it repeat for every column
print(arr1)

[[1 1 1 2 2 2 3 3 3]]


printing a pattern

In [11]:
ar=np.zeros((5,5), dtype='int32')
ar[2,2]=9
ar[:5:4]=1
ar[:,:5:4]=1
print(ar)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


errors while copying

In [12]:
a=np.array([1,2,3])
b=a
print(b)

[1 2 3]


In [13]:
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]


we just changed the first element of b, but the first element of a is also changed....how to get rid of this?

In [14]:
c=a.copy()
c[0]=10
print(a)
print(c)

[100   2   3]
[10  2  3]


when we change the first element of c, the first element of a is not changed