In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(a+2)

[3 4 5 6]


In [5]:
print(a-2)

[-1  0  1  2]


In [6]:
print(a*2)

[2 4 6 8]


In [7]:
print(a/2)

[0.5 1.  1.5 2. ]


In [8]:
b=np.array([1,0,2,0])

In [9]:
a+b

array([2, 2, 5, 4])

In [10]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [11]:
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## linear algebra

In [19]:
a=np.ones((3,2), dtype='int16')
print(a)

b=np.full((2,3),3)
print(b)

[[1 1]
 [1 1]
 [1 1]]
[[3 3 3]
 [3 3 3]]


In [21]:
# inbult matrix multiplication function of numpy
np.matmul(a,b)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [24]:
# finding the determinant of matrix
c=np.identity(3)
np.linalg.det(c) #linalg = linear algebra

1.0

#### statistics:

In [34]:
arr=np.array([[1,21,3,24],[2,5,7,15]])

In [35]:
np.min(arr)

1

In [36]:
np.max(arr)

24

In [37]:
np.min(arr,axis=0)

array([ 1,  5,  3, 15])

In [38]:
np.max(arr,axis=1)

array([24, 15])

In [39]:
np.sum(arr)

78

In [40]:
np.sum(arr,axis=0)

array([ 3, 26, 10, 39])

In [41]:
np.sum(arr,axis=1)

array([49, 29])

#### reorganizing Array

In [42]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
print(arr.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
print(arr.reshape(8,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [50]:
#vertical stacking:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack((v1,v2,v2,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [52]:
np.vstack((v1,v2,v1,v2,v1,v2,v2,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [53]:
#horizental stacking:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.hstack((v1,v1))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [55]:
np.hstack((v1,v2,v2,v1,v1,v2,v2))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4, 1, 2, 3, 4, 5, 6,
       7, 8, 5, 6, 7, 8])